### ISSUE TITLE
Paper and Project Page diagram was not consistent.

### ISSUE THREAD

**Issue by youngstu** [nv-tlabs/GET3D#142]
Paper and Project Page diagram was not consistent. Which is right?

![image](https://github.com/nv-tlabs/GET3D/assets/26452514/0c5b2320-1b4d-464b-aff7-1d1edeb277d0)
![image](https://github.com/nv-tlabs/GET3D/assets/26452514/c1bf37d7-c5ba-412d-822f-a86571673e0e)

**Comment by matbee-eth** [comment]
Logically the bottom image supports a loop and the top image doesnt, so I would /assume/ the bottom is what's happening

**Comment by Bathsheba** [comment]
The top image is as described in the main body of the paper, but if you look in the Appendix they later thought of another model that they like better, that's the default in the code and it is the bottom image.

**Comment by SteveJunGao** [comment]
Yes, we found the bottom one (shared tri-planes) worked better after we submitted the paper. To avoid the major change to the main paper, we chose to keep the main paper unchanged, put the better model (bottom one) in the Appendix, and use it in the code (so that people can try a better model)

Note that, our codebase supports both model architectures, you can play with the first one by simply setting ` --one_3d_generator 0`
