### ISSUE TITLE
Which is better between Triplane representation(Get3D) and Voxel Grid representation(SDFusion)？

### ISSUE THREAD

**Issue by youngstu** [nv-tlabs/GET3D#143]
Which is better between Triplane representation(Get3D) and Voxel Grid representation(SDFusion)？
What are Advantages and disadvantages of different 3D representation methods?

Thanks.

**Comment by SteveJunGao** [comment]
That's a good question. I think, in general, there are pros and cons for each of them:

1. Triplane is more efficient to scale up, because we can generate very high-resolution triplanes to capture more details in geometry and textures, while voxel based representation is hard to scale up because of memory constraints.

2. On the other side, the triplane can have some checker-board artifacts (because the triplane is not an intuitive assumption of the 3D shapes), while the voxel is more intuitive in 3D.
