### ISSUE TITLE
shapenet_chair inference

### ISSUE THREAD

**Issue by dmoham1476** [nv-tlabs/GET3D#51]
I see shapenetcorev1 has chair images. When we run inference on shapenet_chair, I see log messages that ./tmp has 1234 images but I cannot see those. Also val.txt in 3dgan_data_split folder has 573 ids. When we run inference, what is the input image? The fakes_000000_00.png file has 25 generated images. mesh_pred folder has 10 obj files. Can you please explain what is the correlation between these? What was the input image to the inference, in other words, what was the 2D image for which the 3D was generated?

**Comment by SteveJunGao** [comment]
Hi @dmoham1476,

Since we're doing unconditional 3D shape generation, we don't need the input image during the inference, the `val.txt` and `text.txt` are only used for evaluating the performance of our model (e.g. compute the FID, COV, MMD metrics), we don't need to feed in any images into the model to generate 3D shapes. 

In the results, you can see `fakes_000000_00.png` and 10 objs in the `mesh_pred` folder. [This part of the code](https://github.com/nv-tlabs/GET3D/blob/master/training/inference_utils.py#L181-L212) is the place where we save these results, you can check it.  The correspondence between them is: the first 10 images in the `fakes_000000_00.png` corresponds to the 10 objs in the `mesh_pred` folder, note that all of these are generated from a random noise sampled from a Gaussian distribution and we don't need "input image" for the network.

**Comment by dmoham1476** [comment]
How can I use get3D to generate a 3D object for a 2D image?

**Comment by SteveJunGao** [comment]
Hi @SteveJunGao,

We didn't do that in our paper, you can check this issue for more details about it #48

**Comment by dmoham1476** [comment]
Thank you
