### ISSUE TITLE
Is this a mistake when parse the "cammv" from tuple"?

### ISSUE THREAD

**Issue by silence401** [nv-tlabs/GET3D#55]
[network_get3d:466](https://github.com/nv-tlabs/GET3D/blob/6fda9cd15ab78e88db3ba00766df489a3ce88b41/training/networks_get3d.py#L466)
[network_get3d:470](https://github.com/nv-tlabs/GET3D/blob/master/training/networks_get3d.py#L470)

**Comment by SteveJunGao** [comment]
Hi @silence401,

Sorry for the confusion, it was because I hacked the solution when I was doing other debugging that needs the camera to be a tuple in [network_get3d:470](https://github.com/nv-tlabs/GET3D/blob/master/training/networks_get3d.py#L470). I think now in this cleaned codebase the [network_get3d:470](https://github.com/nv-tlabs/GET3D/blob/master/training/networks_get3d.py#L470) won't be called in all the cases, so you can remove it, or change it to the same order as the line [network_get3d:466](https://github.com/nv-tlabs/GET3D/blob/6fda9cd15ab78e88db3ba00766df489a3ce88b41/training/networks_get3d.py#L466) if you want to use it

**Comment by SteveJunGao** [comment]
Close this issue as no update received
