### ISSUE TITLE
Will this work with Ubuntu on windows?

### ISSUE THREAD

**Issue by DuckersMcQuack** [nv-tlabs/GET3D#78]
Where you run it in a virtualized Linux environment like with the earlier stable diffusion infinity.

**Comment by SteveJunGao** [comment]
We haven't tested this on a virtual Linux environment on windows, it would be interesting to see how it can work!

The only concern I have is we need to configure the GPU correctly if running on this kind of virtual machine

**Comment by FilipSivak** [comment]
I can confirm that inference (have not tried training) works inside WSL in Ubuntu with GPU. Note that GPU passthrough to Docker requires up-to-date windows 10 or 11.

I got the following error:
`eglInitialize() failed`

Which is caused by nvdiffrast GL context initialization at `uni_rep\render\neural_renderer.py:60`. The solution is to replace `RasterizeGLContext` with `RasterizeCudaContext`.

**Comment by SteveJunGao** [comment]
Hi @DuckersMcQuack ,

we do plan to release it in the NVIDIA Omniverse soon and it should also support Windows in the future! check this blog for more information https://developer.nvidia.com/blog/rapidly-generate-3d-assets-for-virtual-worlds-with-generative-ai/

**Comment by DuckersMcQuack** [comment]
> Hi @DuckersMcQuack ,
> 
> we do plan to release it in the NVIDIA Omniverse soon and it should also support Windows in the future! check this blog for more information https://developer.nvidia.com/blog/rapidly-generate-3d-assets-for-virtual-worlds-with-generative-ai/

Neat! Never used omniverse before, so that should be interesting!

**Comment by Bathsheba** [comment]
Thanks for the tip @FilipSivak ! 
Can confirm, I too was able to run inference in WSL in Ubuntu with GPU.

**Comment by Bathsheba** [comment]
I can now confirm that training works in this context.
